name: appcenter_sdk_flutter_example
description: Demonstrates how to use the appcenter_sdk_flutter plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  appcenter_sdk_flutter:
    path: ../
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true