// Autogenerated from Pigeon (v5.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif


/// Generated class from Pigeon.

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AppCenterApi {
  func start(secret: String)
  func setEnabled(enabled: Bool, completion: @escaping () -> Void)
  func isEnabled(completion: @escaping (Bool) -> Void)
  func isConfigured() -> Bool
  func getInstallId(completion: @escaping (String) -> Void)
  func isRunningInAppCenterTestCloud() -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AppCenterApiSetup {
  /// The codec used by AppCenterApi.
  /// Sets up an instance of `AppCenterApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AppCenterApi?) {
    let startChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.AppCenterApi.start", binaryMessenger: binaryMessenger)
    if let api = api {
      startChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let secretArg = args[0] as! String
        api.start(secret: secretArg)
        reply(wrapResult(nil))
      }
    } else {
      startChannel.setMessageHandler(nil)
    }
    let setEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.AppCenterApi.setEnabled", binaryMessenger: binaryMessenger)
    if let api = api {
      setEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        api.setEnabled(enabled: enabledArg) {
          reply(wrapResult(nil))
        }
      }
    } else {
      setEnabledChannel.setMessageHandler(nil)
    }
    let isEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.AppCenterApi.isEnabled", binaryMessenger: binaryMessenger)
    if let api = api {
      isEnabledChannel.setMessageHandler { _, reply in
        api.isEnabled() { result in
          reply(wrapResult(result))
        }
      }
    } else {
      isEnabledChannel.setMessageHandler(nil)
    }
    let isConfiguredChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.AppCenterApi.isConfigured", binaryMessenger: binaryMessenger)
    if let api = api {
      isConfiguredChannel.setMessageHandler { _, reply in
        let result = api.isConfigured()
        reply(wrapResult(result))
      }
    } else {
      isConfiguredChannel.setMessageHandler(nil)
    }
    let getInstallIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.AppCenterApi.getInstallId", binaryMessenger: binaryMessenger)
    if let api = api {
      getInstallIdChannel.setMessageHandler { _, reply in
        api.getInstallId() { result in
          reply(wrapResult(result))
        }
      }
    } else {
      getInstallIdChannel.setMessageHandler(nil)
    }
    let isRunningInAppCenterTestCloudChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.AppCenterApi.isRunningInAppCenterTestCloud", binaryMessenger: binaryMessenger)
    if let api = api {
      isRunningInAppCenterTestCloudChannel.setMessageHandler { _, reply in
        let result = api.isRunningInAppCenterTestCloud()
        reply(wrapResult(result))
      }
    } else {
      isRunningInAppCenterTestCloudChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AppCenterAnalyticsApi {
  func trackEvent(name: String, properties: [String: String]?, flags: Int32?)
  func pause()
  func resume()
  func analyticsSetEnabled(enabled: Bool, completion: @escaping () -> Void)
  func analyticsIsEnabled(completion: @escaping (Bool) -> Void)
  func enableManualSessionTracker()
  func startSession()
  func setTransmissionInterval(seconds: Int32) -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AppCenterAnalyticsApiSetup {
  /// The codec used by AppCenterAnalyticsApi.
  /// Sets up an instance of `AppCenterAnalyticsApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AppCenterAnalyticsApi?) {
    let trackEventChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.AppCenterAnalyticsApi.trackEvent", binaryMessenger: binaryMessenger)
    if let api = api {
      trackEventChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nameArg = args[0] as! String
        let propertiesArg = args[1] as? [String: String]
        let flagsArg = args[2] as? Int32
        api.trackEvent(name: nameArg, properties: propertiesArg, flags: flagsArg)
        reply(wrapResult(nil))
      }
    } else {
      trackEventChannel.setMessageHandler(nil)
    }
    let pauseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.AppCenterAnalyticsApi.pause", binaryMessenger: binaryMessenger)
    if let api = api {
      pauseChannel.setMessageHandler { _, reply in
        api.pause()
        reply(wrapResult(nil))
      }
    } else {
      pauseChannel.setMessageHandler(nil)
    }
    let resumeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.AppCenterAnalyticsApi.resume", binaryMessenger: binaryMessenger)
    if let api = api {
      resumeChannel.setMessageHandler { _, reply in
        api.resume()
        reply(wrapResult(nil))
      }
    } else {
      resumeChannel.setMessageHandler(nil)
    }
    let analyticsSetEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.AppCenterAnalyticsApi.analyticsSetEnabled", binaryMessenger: binaryMessenger)
    if let api = api {
      analyticsSetEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        api.analyticsSetEnabled(enabled: enabledArg) {
          reply(wrapResult(nil))
        }
      }
    } else {
      analyticsSetEnabledChannel.setMessageHandler(nil)
    }
    let analyticsIsEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.AppCenterAnalyticsApi.analyticsIsEnabled", binaryMessenger: binaryMessenger)
    if let api = api {
      analyticsIsEnabledChannel.setMessageHandler { _, reply in
        api.analyticsIsEnabled() { result in
          reply(wrapResult(result))
        }
      }
    } else {
      analyticsIsEnabledChannel.setMessageHandler(nil)
    }
    let enableManualSessionTrackerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.AppCenterAnalyticsApi.enableManualSessionTracker", binaryMessenger: binaryMessenger)
    if let api = api {
      enableManualSessionTrackerChannel.setMessageHandler { _, reply in
        api.enableManualSessionTracker()
        reply(wrapResult(nil))
      }
    } else {
      enableManualSessionTrackerChannel.setMessageHandler(nil)
    }
    let startSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.AppCenterAnalyticsApi.startSession", binaryMessenger: binaryMessenger)
    if let api = api {
      startSessionChannel.setMessageHandler { _, reply in
        api.startSession()
        reply(wrapResult(nil))
      }
    } else {
      startSessionChannel.setMessageHandler(nil)
    }
    let setTransmissionIntervalChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.AppCenterAnalyticsApi.setTransmissionInterval", binaryMessenger: binaryMessenger)
    if let api = api {
      setTransmissionIntervalChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let secondsArg = args[0] as! Int32
        let result = api.setTransmissionInterval(seconds: secondsArg)
        reply(wrapResult(result))
      }
    } else {
      setTransmissionIntervalChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AppCenterCrashesApi {
  func generateTestCrash()
  func hasReceivedMemoryWarningInLastSession(completion: @escaping (Bool) -> Void)
  func hasCrashedInLastSession(completion: @escaping (Bool) -> Void)
  func crashesSetEnabled(enabled: Bool, completion: @escaping () -> Void)
  func crashesIsEnabled(completion: @escaping (Bool) -> Void)
  func trackException(message: String, type: String?, stackTrace: String?, properties: [String: String]?)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AppCenterCrashesApiSetup {
  /// The codec used by AppCenterCrashesApi.
  /// Sets up an instance of `AppCenterCrashesApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AppCenterCrashesApi?) {
    let generateTestCrashChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.AppCenterCrashesApi.generateTestCrash", binaryMessenger: binaryMessenger)
    if let api = api {
      generateTestCrashChannel.setMessageHandler { _, reply in
        api.generateTestCrash()
        reply(wrapResult(nil))
      }
    } else {
      generateTestCrashChannel.setMessageHandler(nil)
    }
    let hasReceivedMemoryWarningInLastSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.AppCenterCrashesApi.hasReceivedMemoryWarningInLastSession", binaryMessenger: binaryMessenger)
    if let api = api {
      hasReceivedMemoryWarningInLastSessionChannel.setMessageHandler { _, reply in
        api.hasReceivedMemoryWarningInLastSession() { result in
          reply(wrapResult(result))
        }
      }
    } else {
      hasReceivedMemoryWarningInLastSessionChannel.setMessageHandler(nil)
    }
    let hasCrashedInLastSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.AppCenterCrashesApi.hasCrashedInLastSession", binaryMessenger: binaryMessenger)
    if let api = api {
      hasCrashedInLastSessionChannel.setMessageHandler { _, reply in
        api.hasCrashedInLastSession() { result in
          reply(wrapResult(result))
        }
      }
    } else {
      hasCrashedInLastSessionChannel.setMessageHandler(nil)
    }
    let crashesSetEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.AppCenterCrashesApi.crashesSetEnabled", binaryMessenger: binaryMessenger)
    if let api = api {
      crashesSetEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        api.crashesSetEnabled(enabled: enabledArg) {
          reply(wrapResult(nil))
        }
      }
    } else {
      crashesSetEnabledChannel.setMessageHandler(nil)
    }
    let crashesIsEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.AppCenterCrashesApi.crashesIsEnabled", binaryMessenger: binaryMessenger)
    if let api = api {
      crashesIsEnabledChannel.setMessageHandler { _, reply in
        api.crashesIsEnabled() { result in
          reply(wrapResult(result))
        }
      }
    } else {
      crashesIsEnabledChannel.setMessageHandler(nil)
    }
    let trackExceptionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.AppCenterCrashesApi.trackException", binaryMessenger: binaryMessenger)
    if let api = api {
      trackExceptionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let messageArg = args[0] as! String
        let typeArg = args[1] as? String
        let stackTraceArg = args[2] as? String
        let propertiesArg = args[3] as? [String: String]
        api.trackException(message: messageArg, type: typeArg, stackTrace: stackTraceArg, properties: propertiesArg)
        reply(wrapResult(nil))
      }
    } else {
      trackExceptionChannel.setMessageHandler(nil)
    }
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: FlutterError) -> [Any?] {
  return [
    error.code,
    error.message,
    error.details
  ]
}
